"use strict";

window.BTECH_PACKAGE = Object.freeze({
  id: "infinite-ultimate-max",
  name: "BTECH-TV INFINITE ULTIMATE MAX",
  displayName: "5,000,000 Channels",
  channelLimit: 5000000,
  price: 2999.99,
  currency: "USD",

  features: [
    "5,000,000+ Live TV Channels",
    "Worldwide Channel Coverage",
    "Global Sports Networks",
    "Movies & Entertainment",
    "International News",
    "Music & Radio",
    "Kids & Family Channels",
    "Documentary & Educational Channels",
    "Religious Channels",
    "Multi-Language Channels",
    "Unlimited Favorites",
    "Recently Watched History",
    "Advanced Global Search",
    "Picture-in-Picture",
    "Fullscreen Streaming",
    "Ultra Stream Optimization",
    "Intelligent Stream Repair",
    "Global Ultra Feeds",
    "Automatic Stream Recovery",
    "Advanced Memory Optimization",
    "Advanced Streaming Engine",
    "Enhanced Stream Stability",
    "Multi-Source Feed Support",
    "Maximum Channel Processing",
    "Advanced Feed Management",
    "Global Feed Distribution",
    "Intelligent Channel Indexing",
    "Ultimate Max Performance",
    "Advanced Global Analytics",
    "Intelligent Channel Management",
    "Extreme Feed Processing",
    "Advanced Session Management",
    "Maximum Feed Optimization",
    "Enterprise-Scale Channel Engine",
  ],
});
